# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EmergencyApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EmergencyApp
  pod 'GooglePlaces'
  pod 'GoogleMaps'
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Core'
  pod 'Firebase/Storage'
  pod 'Firebase/Firestore'
  pod 'MessageKit','~> 2.0.0'
  pod 'FanMenu'
  pod 'CountryPickerView'


end
